/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface InvestigationHelperInterface extends utils.Interface {
  functions: {
    "echo(string)": FunctionFragment;
    "emitEvent()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "echo" | "emitEvent"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "echo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "emitEvent", values?: undefined): string;

  decodeFunctionResult(functionFragment: "echo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "emitEvent", data: BytesLike): Result;

  events: {
    "TokenEvent(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokenEvent"): EventFragment;
}

export interface TokenEventEventObject {
  sender: string;
}
export type TokenEventEvent = TypedEvent<[string], TokenEventEventObject>;

export type TokenEventEventFilter = TypedEventFilter<TokenEventEvent>;

export interface InvestigationHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InvestigationHelperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    echo(
      input: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    emitEvent(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  echo(
    input: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  emitEvent(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    echo(
      input: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    emitEvent(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "TokenEvent(address)"(sender?: null): TokenEventEventFilter;
    TokenEvent(sender?: null): TokenEventEventFilter;
  };

  estimateGas: {
    echo(
      input: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    emitEvent(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    echo(
      input: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    emitEvent(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
